// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Katz.Web.Website.Tests.Integration.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "database")]
    [Xunit.TraitAttribute("Category", "web")]
    public partial class SearchBooksFeature : object, Xunit.IClassFixture<SearchBooksFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "database",
                "web"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SearchBooks.feature"
#line hidden
        
        public SearchBooksFeature(SearchBooksFeature.FixtureData fixtureData, Katz_Web_Website_Tests_Integration_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SearchBooks", "\tIn order to make sense of my collection\r\n\tAs a collector\r\n\tI want to be able to " +
                    "search my collection", ProgrammingLanguage.CSharp, new string[] {
                        "database",
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search for books without title")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchBooks")]
        [Xunit.TraitAttribute("Description", "Search for books without title")]
        public virtual void SearchForBooksWithoutTitle()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for books without title", null, ((string[])(null)));
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title",
                            "Author",
                            "Description",
                            "Rating",
                            "Series"});
                table2.AddRow(new string[] {
                            "Harry Potter 1",
                            "JK Rowling",
                            "Boy wizard",
                            "4",
                            "harry"});
                table2.AddRow(new string[] {
                            "Harry Potter 2",
                            "JK Rowling",
                            "Limited Edition 1",
                            "3",
                            "Fantasy"});
                table2.AddRow(new string[] {
                            "Harry Potter 3",
                            "JK Rowling",
                            "Limited Edition 2",
                            "4",
                            "Fantasy"});
                table2.AddRow(new string[] {
                            "Harry Potter 4",
                            "JK Rowling",
                            "Limited Edition 3",
                            "4",
                            "harry"});
                table2.AddRow(new string[] {
                            "Harry Potter 5",
                            "JK Rowling",
                            "Limited Edition 4",
                            "5",
                            "Fantasy"});
#line 9
 testRunner.Given("There are books", ((string)(null)), table2, "Given ");
#line hidden
#line 16
 testRunner.And("I am on the search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Author",
                            "Title",
                            "Rating",
                            "Series"});
                table3.AddRow(new string[] {
                            "JK Rowling",
                            "",
                            "4",
                            "harry"});
#line 17
 testRunner.When("I search for", ((string)(null)), table3, "When ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title",
                            "Author",
                            "Rating",
                            "Series"});
                table4.AddRow(new string[] {
                            "Harry Potter 1",
                            "JK Rowling",
                            "4",
                            "harry"});
                table4.AddRow(new string[] {
                            "Harry Potter 4",
                            "JK Rowling",
                            "4",
                            "harry"});
#line 20
 testRunner.Then("I will see the following results", ((string)(null)), table4, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Search for books with title")]
        [Xunit.TraitAttribute("FeatureTitle", "SearchBooks")]
        [Xunit.TraitAttribute("Description", "Search for books with title")]
        public virtual void SearchForBooksWithTitle()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for books with title", null, ((string[])(null)));
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title",
                            "Author",
                            "Description",
                            "Rating",
                            "Series"});
                table5.AddRow(new string[] {
                            "Book",
                            "JK Rowling",
                            "description",
                            "4",
                            "harry"});
                table5.AddRow(new string[] {
                            "Book",
                            "Somebody Else",
                            "description 2",
                            "3",
                            "Action"});
                table5.AddRow(new string[] {
                            "Another Book",
                            "Somebody Else",
                            "description 3",
                            "3",
                            ""});
#line 26
 testRunner.Given("There are books", ((string)(null)), table5, "Given ");
#line hidden
#line 31
 testRunner.And("I am on the search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title"});
                table6.AddRow(new string[] {
                            "Book"});
#line 32
 testRunner.When("I search for", ((string)(null)), table6, "When ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Title",
                            "Author",
                            "Rating",
                            "Series"});
                table7.AddRow(new string[] {
                            "Book",
                            "JK Rowling",
                            "4",
                            "harry"});
                table7.AddRow(new string[] {
                            "Book",
                            "Somebody Else",
                            "3",
                            "Action"});
#line 35
 testRunner.Then("I will see the following results", ((string)(null)), table7, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SearchBooksFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SearchBooksFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
